version: '3'

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_librarify:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - librarifyback_app_sync:/var/www/librarify/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - librarifyback_app_sync:/var/www/librarify/
        ports:
            - 80:80
        networks:
            - symfony

volumes:
    librarifyback_app_sync:
        external: true
    db_librarify:

networks:
    symfony:
